const status=document.querySelector('#status'),cameras=document.querySelector('#cameras'),zones=document.querySelector('#zones'),fusionStatus=document.querySelector('#fusion-status'),environmentStatus=document.querySelector('#environment-status');
const labels=['Stationary','Low','Medium','High'],cards=new Map();let assignments={};
function cameraCard(id,name=id){if(cards.has(id))return cards.get(id);const element=document.createElement('div');element.className='camera';element.innerHTML=`<div class="camhead"><b>${name}</b><span class="fps">Waiting</span></div><label class="zone-picker">Camera coverage zone <select><option value="">Not assigned</option><option value="zone-1">Zone 1 · North West</option><option value="zone-2">Zone 2 · North East</option><option value="zone-3">Zone 3 · South West</option><option value="zone-4">Zone 4 · South East</option></select></label><img class="preview" alt="${name} processed video"><strong class="count">0</strong> tracked people <div class="tracks">Awaiting frames…</div>`;const select=element.querySelector('select');select.value=assignments[id]||'';select.onchange=async()=>{const zone_id=select.value||null;const response=await fetch(`/api/camera-zones/${id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({zone_id})});if(response.ok)assignments=await response.json()};cameras.classList.remove('empty');cameras.append(element);const card={image:element.querySelector('.preview'),fps:element.querySelector('.fps'),count:element.querySelector('.count'),tracks:element.querySelector('.tracks'),loading:false,lastPreview:0,url:null};cards.set(id,card);return card}
async function refreshPreview(id,card){const now=Date.now();if(card.loading||now-card.lastPreview<200)return;card.loading=true;try{const response=await fetch(`/api/cameras/${id}/frame.jpg?${now}`,{cache:'no-store'});if(!response.ok)return;const nextUrl=URL.createObjectURL(await response.blob()),priorUrl=card.url;card.image.onload=()=>{if(priorUrl)URL.revokeObjectURL(priorUrl)};card.image.src=nextUrl;card.url=nextUrl;card.lastPreview=now}finally{card.loading=false}}
function renderZones(items){zones.innerHTML=items.map(z=>`<div class="zone"><b>${z.name}</b><span>${z.people_count||0} people · ${z.device_load_w||0} W devices</span><span>${z.light_count||0} lights · ${z.lighting_load_w||0} W</span><span>${Object.entries(z.activity_levels||{}).filter(([,n])=>n).map(([a,n])=>`${n} ${a}`).join(' · ')||'No activity observed'}</span></div>`).join('')}
Promise.all([fetch('/api/cameras').then(r=>r.json()),fetch('/api/camera-zones').then(r=>r.json())]).then(([items,zones])=>{assignments=zones;items.filter(c=>c.enabled).forEach(c=>cameraCard(c.id,c.name))});
async function refreshWeather(){const response=await fetch('/api/weather/current');const value=await response.json();environmentStatus.textContent=response.ok?`${value.location.name} · ${value.outdoor_temperature} °C outside · ${value.outdoor_humidity}% RH · wind ${value.wind_speed} km/h · solar ${value.solar_radiation??'n/a'} W/m² · live API`:`Weather: ${value}`}
document.querySelector('#location-form').onsubmit=async event=>{event.preventDefault();const query=document.querySelector('#location-query').value;const response=await fetch('/api/location',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({query})});const value=await response.json();if(!response.ok){environmentStatus.textContent=`Location: ${value}`;return}environmentStatus.textContent=`Room location set to ${value.name} (${value.latitude}, ${value.longitude}). Loading weather…`;refreshWeather()};
document.querySelector('#weather-refresh').onclick=refreshWeather;
document.querySelector('#indoor-load').onclick=async()=>{const response=await fetch('/api/environment/indoor/room-occupancy-detection');const value=await response.json();environmentStatus.textContent=response.ok?`Historical occupancy dataset · ${value.indoor_temperature} °C · ${value.indoor_humidity}% RH · CO₂ ${value.indoor_co2} · occupancy ${value.occupancy}`:`Indoor dataset: ${value}`};
const ws=new WebSocket(`ws://${location.host}/ws/live`);
ws.onopen=()=>{status.textContent='Live';status.className='live';ws.send('ready')};ws.onclose=()=>{status.textContent='Offline';status.className='offline'};
ws.onmessage=e=>{const message=JSON.parse(e.data);if(message.type==='room')renderZones(message.data.zones.map(z=>({...z,people_count:0,device_load_w:0,light_count:0,lighting_load_w:0})));if(message.type==='zone_state')renderZones(message.data.zones);if(message.type==='fusion_state'){const d=message.data;fusionStatus.textContent=`${d.people_count} distinct people · ${d.mode==='unconfigured'?'no verified camera overlap configured':d.mode.replace('_',' ')} · ${d.people.filter(p=>p.fusion_status==='merged').length} cross-camera matches`};if(message.type==='camera_frame_result'){const data=message.data,card=cameraCard(data.camera_id),tracks=data.tracks;card.fps.textContent=`${data.fps} FPS`;card.count.textContent=tracks.length;card.tracks.innerHTML=tracks.map(t=>`<span>#${t.id.split(':')[1]} · ${labels[t.activity]} · ${t.motion_score}px</span>`).join('')||'No people detected';refreshPreview(data.camera_id,card)}};
